/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  governance_library: () => import("@/views/governance/library/index.vue"),
  "governance_review-workflow": () => import("@/views/governance/review-workflow/index.vue"),
  governance_review: () => import("@/views/governance/review/index.vue"),
  governance_rules: () => import("@/views/governance/rules/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  operations_ops: () => import("@/views/operations/ops/index.vue"),
  operations_org: () => import("@/views/operations/org/index.vue"),
  school_assets: () => import("@/views/school/assets/index.vue"),
  "workflow_script-review": () => import("@/views/workflow/script-review/index.vue"),
  workflow_tasks: () => import("@/views/workflow/tasks/index.vue"),
  workflow_workspace: () => import("@/views/workflow/workspace/index.vue"),
};
