/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'governance',
    path: '/governance',
    component: 'layout.base',
    meta: {
      title: 'governance',
      i18nKey: 'route.governance',
      icon: 'mdi:shield-check-outline',
      order: 3
    },
    children: [
      {
        name: 'governance_library',
        path: '/governance/library',
        component: 'view.governance_library',
        meta: {
          title: 'governance_library',
          i18nKey: 'route.governance_library',
          icon: 'mdi:folder-play-outline',
          order: 2
        }
      },
      {
        name: 'governance_review',
        path: '/governance/review',
        component: 'view.governance_review',
        meta: {
          title: 'governance_review',
          i18nKey: 'route.governance_review',
          icon: 'mdi:file-search-outline',
          order: 1
        }
      },
      {
        name: 'governance_review-workflow',
        path: '/governance/review-workflow',
        component: 'view.governance_review-workflow',
        meta: {
          title: 'governance_review-workflow',
          i18nKey: 'route.governance_review-workflow'
        }
      },
      {
        name: 'governance_rules',
        path: '/governance/rules',
        component: 'view.governance_rules',
        meta: {
          title: 'governance_rules',
          i18nKey: 'route.governance_rules'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:compass-rose',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'operations',
    path: '/operations',
    component: 'layout.base',
    meta: {
      title: 'operations',
      i18nKey: 'route.operations',
      icon: 'mdi:cog-outline',
      order: 5
    },
    children: [
      {
        name: 'operations_ops',
        path: '/operations/ops',
        component: 'view.operations_ops',
        meta: {
          title: 'operations_ops',
          i18nKey: 'route.operations_ops',
          icon: 'mdi:chart-line',
          order: 2
        }
      },
      {
        name: 'operations_org',
        path: '/operations/org',
        component: 'view.operations_org',
        meta: {
          title: 'operations_org',
          i18nKey: 'route.operations_org',
          icon: 'mdi:account-group-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'school',
    path: '/school',
    component: 'layout.base',
    meta: {
      title: 'school',
      i18nKey: 'route.school',
      icon: 'mdi:school-outline',
      order: 4
    },
    children: [
      {
        name: 'school_assets',
        path: '/school/assets',
        component: 'view.school_assets',
        meta: {
          title: 'school_assets',
          i18nKey: 'route.school_assets',
          icon: 'mdi:image-multiple-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'workflow',
    path: '/workflow',
    component: 'layout.base',
    meta: {
      title: 'workflow',
      i18nKey: 'route.workflow',
      icon: 'mdi:creation-outline',
      order: 2
    },
    children: [
      {
        name: 'workflow_script-review',
        path: '/workflow/script-review',
        component: 'view.workflow_script-review',
        meta: {
          title: 'workflow_script-review',
          i18nKey: 'route.workflow_script-review',
          icon: 'mdi:script-text-outline',
          order: 2
        }
      },
      {
        name: 'workflow_tasks',
        path: '/workflow/tasks',
        component: 'view.workflow_tasks',
        meta: {
          title: 'workflow_tasks',
          i18nKey: 'route.workflow_tasks',
          icon: 'mdi:timeline-clock-outline',
          order: 3
        }
      },
      {
        name: 'workflow_workspace',
        path: '/workflow/workspace',
        component: 'view.workflow_workspace',
        meta: {
          title: 'workflow_workspace',
          i18nKey: 'route.workflow_workspace',
          icon: 'mdi:lightbulb-on-outline',
          order: 1
        }
      }
    ]
  }
];
